#!/usr/bin/env bash
set -e

block=$(seth block latest number)
block=$(($block - 50))
block=$(seth --to-hex $block)

seth logs-rpc --follow $OASIS $block |

while read -r event;
do
  topics=$(echo $event | jq '.topics')
  block=$(echo $event | jq -r '.blockNumber')
  id=$(echo $event | jq -r '.topics[1]')
  if [[ "$id" != "null" ]]; then
    dec=$(seth --to-dec $id);
    if [[ "${#dec}" -lt 8 ]]; then
      echo "> $dec"
      oasis --cache-offer $dec $block &
    else
      echo "> Unknown event"
      echo $topics
    fi
  fi
done


